FROM ollama/ollama:latest

RUN apt-get update && apt-get install -y --no-install-recommends \
    curl \
    && rm -rf /var/lib/apt/lists/*

# Copy your custom modelfile
COPY models/Modelfile /Modelfile

# Copy startup script
COPY ./startollama.sh /start.sh
RUN chmod +x /start.sh

EXPOSE 11434
ENTRYPOINT ["/start.sh"]
